-- AlterTable
ALTER TABLE "Settings"
ADD COLUMN IF NOT EXISTS "profitMarginGamesPct" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "profitMarginGiftCardsPct" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "profitMarginPsPlusPct" DOUBLE PRECISION NOT NULL DEFAULT 20;

